### ISSUE TITLE
Cambio manuale delle righe in fattura

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#13]
Supponiamo di creare una fattura qualunque utilizzando indistintamente uno dei due metodi supportati da EasyDDT.  
La fattura creata sarà una fattura in stato “Bozza”; questo comporta che, a livello teorico, si possano cambiare manualmente le quantità delle righe o, addirittura, rimuovere un’intera riga dalla fattura stessa.

Questa eventualità appena descritta, viene correttamente gestita dal normale flusso di fatturazione di Odoo in quanto, le quantità calcolate presenti sulle singole righe d’ordine (tra cui `qty_to_invoice` e `qty_invoiced`) verranno aggiornate istantaneamente senza alcun problema.  
Questo, però, non accade nel caso delle righe presenti nel DdT che vengono, invece, ritenute come ormai già fatturate e che quindi non verranno più prese in considerazione nelle successive iterazioni di fatturazione.

Lo scenario si complica ulteriormente nel caso in cui, nella fattura appena modificata manualmente, siano coinvolte più picking associate a DdT differenti; anche se intercettassi l’evento di modifica di una riga, su quale dei due DdT dovrei intervenire?

**Comment by MarcoCalcagni** [comment]
Ciao @Byloth , se cambi qualcosa in fattura si dovrebbe aggiornare solo il sale order mai il picking/ddt . 

una volta che hai fatto la spedizione il ddt non dovrebbe essere mai variato. se lo cambi perchè hai cambiato la fattura avresti un documento non corrispondente con quello generato in precedenza. 

es. spedisco 3 pezzi , il cliente ne contesta uno difettoso , gli amministrativi ne fatturano 2 , ma il magazzino comunque ne ha spediti 3.

**Comment by Byloth** [comment]
UUUH! Ok! Giusto!  
Informazione importantissima!

Probabilmente, si potrebbe lasciare così com'è, allora...  
Ti descrivo quello che accade così puoi confermarmi, o meno, se la logica è corretta.

---

Qualora dovessi eseguire delle modifiche alla fattura successive alla sua emissione, il DdT non si aggiornerebbe automaticamente: quello che era stato flaggato come "Fatturato" rimane "Fatturato" (anche se rimosso dalla fattura).

Viene data, però, la possibilità all'utente di riallineare, eventualmente, lo stato di cos'è stato fatturato o meno tra l'ordine di vendita e il DdT forzando l'annullamento e il ripristino in bozza del DdT stesso.  
Questa operazione, però, è consentita esclusivamente se non sono presenti fatture legate al DdT che si sta cercando di annullare.

Quindi, in sostanza, il tutto mi sembra rimanga coerente con quanto hai evidenziato nel tuo precedente commento.  
Non credo ci sia nulla da modificare.

Sei d'accordo?

**Comment by Byloth** [comment]
Perfetto!  
Chiudo la Issue.
