### ISSUE TITLE
note varie 

### ISSUE THREAD

**Issue by MarcoCalcagni** [DinamicheAziendali/l10n_it_delivery_note#14]
in modalità non avanzata 
non si vede in numero di ddt nella form e nella tree
note interne -> note ddt 
se possibile eliminerei il button standard odoo per la stampa quando il picking è validato.
il tab ddt lo metterei in prima posizione . 

Report 
data trasporto colli condizioni dovrebbero andare alla fine 
il numeratore va impostato meglio

**Comment by Byloth** [comment]
@As400it, puoi farmi un favore?

Potresti aprire una nuova Issue in cui descrivi nei dettagli cosa intendi con:
>  il numeratore va impostato meglio

---

Tutti gli altri punti di questa Issue sono stati separati in ulteriori Issue.  
Una volta aperta la Issue sopracitata, sentiti libero di chiudere questa.

**Comment by Byloth** [comment]
Da call con @As400it, l'ultimo punto da chiarire appare risolto.

Chiudo la Issue.
