### ISSUE TITLE
Script di migrazione per `easy_ddt`

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#15]
A seguito della ridenominazione del modulo (Issue #12), è stato commentato il codice di migrazione dalla vecchia versione di `easy_ddt` a quella nuova.

- Se si reputano fondamentali queste logiche, per garantire la "retrocompatibilità" per le istanze con la vecchia versione di `easy_ddt` installata, dovrà essere necessario adattare queste logiche ad un comando CLI da creare ad-hoc.
- Se, invece, si reputano tali logiche superflue o non risultano essere necessarie, dovranno essere eliminate e rimosse dal codice sorgente.

**Comment by Byloth** [comment]
@As400it: credo proprio tu sia l'unico che possa dare una risposta a questo quesito.

Hai bisogno di garantire la retrocompatibilità con eventuali vecchie istanze oppure ce ne possiamo "sbattere" e rimuovere, semplicemente, queste logiche?

**Comment by MarcoCalcagni** [comment]
> @As400it: credo proprio tu sia l'unico che possa dare una risposta a questo quesito.
> 
> Hai bisogno di garantire la retrocompatibilità con eventuali vecchie istanze oppure ce ne possiamo "sbattere" e rimuovere, semplicemente, queste logiche?

la seconda certamente . in questa fase conviene andare avanti e avere una buona base di partenza poi vediamo cosa succede. il codice lascialo pure commentato può essere di ispirazione per nuovi volontari
