### ISSUE TITLE
error printing ddt - no company_id

### ISSUE THREAD

**Issue by andreampiovesana** [DinamicheAziendali/l10n_it_delivery_note#20]
Error to render compiling AST
AttributeError: 'stock.delivery.note' object has no attribute 'company_id'
Template: l10n_it_delivery_note.delivery_note_report_template
Path: /templates/t/t/t[2]/p/t
Node: <t t-esc="doc.company_id.country_id.vat_label or 'Tax ID'"/>:

**Comment by Byloth** [comment]
Questo errore non dovrebbe più essere presente.  
Quantomeno... Riesco ad eseguire le stampe correttamente.

Datemi un feedback.

**Comment by MarcoCalcagni** [comment]
Ok risolto
