### ISSUE TITLE
missing show_price and show_deadline_date

### ISSUE THREAD

**Issue by andreampiovesana** [DinamicheAziendali/l10n_it_delivery_note#21]
need porting in form and report

**Comment by MarcoCalcagni** [comment]
ciao Andrea , 
l'aggiunta di queste info potrebbe essere un modulo a parte che si integra con il delivery note di base questo perchè non a tutti potrebbe andar bene di avere il prezzo visibile ai magazziniere.  
che ne pensi ?
Lo faresti tu questo moduletto

**Comment by andreampiovesana** [comment]
credo debba essere una funzionalità di base perchè i prezzi di default dovrebbero essere nascosti per i magazzinieri e anche in stampa dei ddt

**Comment by Byloth** [comment]
Perdonami, @andreampiovesana...
Forse non ho compreso la tua richiesta!

Prezzi, sconti e tasse vengono già mostrate (o nascoste) sulla base di una configurazione...
![image](https://user-images.githubusercontent.com/14953974/82880781-2cb46f80-9f3f-11ea-9792-6a117c67d2d8.png)

---

Non è questo di cui hai bisogno? 🤔

**Comment by andreampiovesana** [comment]
dovrei abilitarle per utente

non le metterei nei settings

se mai su ciascun documento posso indicare se lo voglio con i prezzi


Andrea Piovesana Linux Mint 19.3www.pnlug.it



Il giorno mar 26 mag 2020 alle ore 10:55 Matteo Bilotta <
notifications@github.com> ha scritto:
