### ISSUE TITLE
Possibile nascondere il partner nei trasferimenti interni?

### ISSUE THREAD

**Issue by GSLabIt** [DinamicheAziendali/l10n_it_delivery_note#22]

**Comment by Byloth** [comment]
La richiesta sembra avere, perfettamente, senso.

@GSLabIt e @As400it...  
Sicuramente, voi, ne sapete più del sottoscritto...

Come posso distinguere un trasferimento interno (e quindi nascondere in interfaccia il campo) rispetto ad un altro tipo di consegna?

**Comment by GSLabIt** [comment]
Potresti aggiungere un flag nell'operazione trasferimento interno e nascondere il partner se è true, oppure si potrebbe verificare location origine e destinazione se sono entrambe magazzini interni si potrebbe nascondere il partner. 

Probabilmente il flag fuga ogni dubbio ..

**Comment by MarcoCalcagni** [comment]
mergiato
