### ISSUE TITLE
Valutare la gestione dei DdT fornitore

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#3]
## Issue legata a #1 ##

Valutare la possibilità di aggiungere e gestire correttamente i DdT fornitore in ingresso all'azienda.

Probabilmente, dovranno essere sottoposti a logiche differenti, la numerazione dovrà essere inserita manualmente anzichè essere fornita automaticamente dal sistema.  
Inoltre, potrebbe aver senso dividere in maniera netta i DdT fornitori utilizzando, fisicamente, dei modelli differenti (onde evitare problemi).

**Comment by Byloth** [comment]
Sia @andreampiovesana che @GrassoPao hanno chiesto se, questa feature, è già presente e gestita.

Al momento, out-of-the-box, non è gestita; alla stessa maniera, però, non ci sono particolari limitazioni nell'utilizzo.
È necessario provare ad utilizzare il modulo con questo fine, capire quali sono i problemi principali riscontrati e le eventuali limitazioni.

Da definire, poi, futuri sviluppi ed implementazioni.

**Comment by MarcoCalcagni** [comment]
second o me dovrebbe essere un modulo a parte che dipende da easyddt. 

lo scenario che io conosco è questo, il fornitore consegna la merce , il magazziniere registra su odoo (stavo scrivendo sistema :-) ) e poi stampa la BEM Buono Entrata Merce che allega alla ddt fornitore che poi va allegata alla fattura. nel Bem spesso sono aggiunte una serie di info che sono tipiche dell'azienda es. ubicazione dei prodotti , dei codici per far rispettare il fifo , barcode per successivi usi ecc. 
di solito i BEM vengono usati in grosse aziende con magazzini importanti . 

credo che da fare sia abbastanza semplice , è il report del picking quando consegna il fornitore. 
va aggiunta il numero ddt fornitore (riferimento) e la data ddt fornitore .

**Comment by Byloth** [comment]
Sono d'accordo riguardo l'implementazione di questa feature in un modulo a parte...  
Mentre, per quanto riguarda tutto il tuo discorso relativo al BEM, faccio finta di aver capito ed annuisco! 😁

>  *(Ho **indubbiamente** bisogno di un minimo di contesto funzionale in più, per comprendere...* 😕

---

Mi chiedo se, addirittura, non si debba cambiare la gerarchia di dipendenze di `easy_ddt` stesso...

Della serie:
 - Esiste un modulo base, come si era ipotizzato, che esprime solo i modelli (un ipotetico `easy_ddt_base`).
 - `easy_ddt` dipende da `easy_ddt_base`.
 - Questo nuovo modulo per i DdT fornitore non dipende da `easy_ddt` ma da `easy_ddt_base`.

Ma, a mio parere, è ancora presto per prevedere un comportamento del genere...  
Soprattutto, non avendo capito un accidenti del comportamento descritto! 😅

**Comment by MarcoCalcagni** [comment]
> Della serie:
> 
> * Esiste un modulo base, come si era ipotizzato, che esprime solo i modelli (un ipotetico `easy_ddt_base`).
> * `easy_ddt` dipende da `easy_ddt_base`.
> * Questo nuovo modulo per i DdT fornitore non dipende da `easy_ddt` ma da `easy_ddt_base`.
> 

questo che hai descritto è perfetto ed è quello che vorrei, in questo modo ogni contesto avrà il suo modulo.

**Comment by pigna74** [comment]
Sono perfettamente d'accordo di considerare un modulo/progetto a parte. Non so neanche se valga la pena di farlo dipendere da easy ddt. Da verificare se e come gestiscono un caso simile fuori dall'Italia

**Comment by Byloth** [comment]
Dalla call che si è tenuta in data odierna, @stevech091 ha proposto di non creare un nuovo modulo a parte, per implementare questa funzionalità, ma di affogarla all'interno del modulo base.  
Potrebbe, assolutamente, trattarsi di una giusta osservazione.

Trovo, però, che sia necessario definire le funzionalità necessarie e richieste prima di scegliere se implementare il tutto in un modulo nuovo a parte o meno.

Da definire.
