### ISSUE TITLE
Valutare comportamento migrazione da `l10n_it_ddt`

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#30]
Attualmente, la migrazione dei dati, si basa esclusivamente sulle picking associate ai "vecchi" DdT.  
Nel caso in cui, infatti, per i documenti precedenti siano presenti solo righe senza che vi siano stati associati i relativi picking, non vengono riportate le righe all'interno dei nuovi documenti.

Valutare il comportamento da adottare in questi casi.

**Comment by andreampiovesana** [comment]
io direi di convertirli se move_id = null

move_id = NULL
package_preparation_id → delivery_note_id
sequence → sequence
product_id → product_id
name → name
product_id → product_id
product_uom_qty → product_qty
product_uom_id → product_uom_id
price_unit (from related)
currency_id (from related)
discount (from related)

only old:
    • lot_id (from move_id)
    • note (now note and section in new line)

only new:
    • display_name (necessary ?)
    • price_unit
    • currency_id
    • discount
    • sale_line_id
    • purchase_line_id
    • invoice_status

**Comment by Byloth** [comment]
La tua proposta mi piace, @andreampiovesana!

La integro con alcune mie piccole correzioni e riscrivo il formato completo della conversione dei dati:
- `package_preparation_id` → `delivery_note_id`
- `sequence` → `sequence`
- `name` → `name`
- `product_id` → `product_id`
- `product_uom_qty` → `product_qty`
- `product_uom_id` → `product_uom_id`
- `price_unit` → `price_unit`
- `discount` → `discount`
- `tax_ids` → `tax_ids`

Tutti gli altri campi, presenti solo nel vecchio modello oppure solo nel nuovo e senza un campo corrispettivo, potranno essere ignorati senza problemi (secondo la mia opinione).

---

Tale conversione di questi dati dovrà essere eseguita **esclusivamente** sulle righe con `move_id = None`; tutte le altre, rientrano nel flusso standard di migrazione già implementato.

**Comment by Byloth** [comment]
Flaggo la Issue come "Pronta per lo sviluppo".

Chiunque avrà del tempo da dedicarci, si senta libero di portare avanti lo sviluppo tramite una PR (possibilmente, avvisando con un commento, per evitare che in più persone si lavori inutilmente sullo stesso sviluppo).
Se qualcun altro, invece, dovesse avere altre opinioni a riguardo, non esiti a commentare ulteriormente questa Issue con le sue osservazioni.

**Comment by Byloth** [comment]
@andreampiovesana: implementato.  

Testato personalmente e sembra funzionare...  
Prova a fare un test e fammi sapere se ti torna tutto.

**Comment by GSLabIt** [comment]
@Byloth possibile sapere come lanciare il comando? ho provato come da readme:
 
`./odoo-bin migrate_ddt_data --database mydb` 

ma continua a darmi errore: `Unknow command 'migrade_ddt_data'`

suggerimenti? grazie
