### ISSUE TITLE
errore su ordine cliente non carica dati listino e altro

### ISSUE THREAD

**Issue by andreampiovesana** [DinamicheAziendali/l10n_it_delivery_note#57]
Se crei un nuovo ordine di vendita non cambia i campi indirizzo fattura, indirizzo di consegna, listino prezzi e valuta in automatico. Si devono impostare a mano. (da Giuseppe Stoduto)

**Comment by Byloth** [comment]
Risolto!  
Grazie per aver aperto un ticket di segnalazione! 😉
