### ISSUE TITLE
integrazione efattura

### ISSUE THREAD

**Issue by andreampiovesana** [DinamicheAziendali/l10n_it_delivery_note#58]
modulo l10n_it_fatturapa_out_ddt
che permette export dati ddt su fattura elettronica
cosa facciamo?

**Comment by Byloth** [comment]
Come già detto durante lo sprint, non è da portare; possiamo ignorarlo.

`l10n_it_delivery_note` gestisce già nativamente l'aggiunta delle informazioni del DdT all'interno della fattura, come semplici righe descrittive (le quali vengono già esportate correttamente in eFattura).

Le righe descrittive, inserite in fattura, hanno il seguente formato:
```
DdT N° XXX/NNNNN del GG/MM/AAAA
```

---

Da quanto è emerso dallo sprint, non ci **dovrebbero** essere altre esigenze funzionali, in termini legali; siamo compliant.

Chiudo il ticket.
