### ISSUE TITLE
Inserire il tasto DDT in alto a destra nella view dell'ordine

### ISSUE THREAD

**Issue by GrassoPao** [DinamicheAziendali/l10n_it_delivery_note#6]
Utile a visualizzare il/i ddt legati all'ordine, oltre a essere molto più intuitivo, allo stato attuale viene difficile capire quanti e quali ddt sono legati all'ordine.

**Comment by Byloth** [comment]
Come giustamente evidenziato, è stata introdotta la visualizzazione e la gestione dei DdT direttamente dall'ordine di vendita.

Puoi chiudere questa Issue.
