### ISSUE TITLE
Implementare funzionalità multi-company

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#60]
In seguito dell'apertura della Issue #59 da parte di @andreampiovesana, apro questa Issue (e chiudo la precedente) così da tradurre in un Italiano corrente e linguaggio leggibile da chiunque quanto ho intuito (credo) dalla Issue citata.

Si richiede l'implementazione e la gestione di tutte le funzionalità del DdT anche su un'istanza di Odoo configurata per il multi-company.

---

@andreampiovesana: sentiti libero di scrivere le Issue in Italiano, se può servire ad avere delle descrizioni chiare per tutti.

Grazie.

**Comment by Byloth** [comment]
Per quanto riguarda l'implementazione di questa Issue, credete basti semplicemente aggiungere al modello `stock.delivery.note` il campo `company_id`?  
Oppure è necessario altro?

Non ho esperienza diretta con database multi-company, purtroppo... 🤔

**Comment by andreampiovesana** [comment]
per la modifica guarda qui:
https://github.com/odoo/odoo/pull/38369/files

**Comment by Byloth** [comment]
Perfetto, @andreampiovesana...  
Se basta aggiungere una foreign-key al modello e la relativa `ir.rule`, allora non serve ulteriore analisi.

Flaggo la Issue come "Pronta per lo sviluppo".

Chiunque avrà del tempo da dedicarci, si senta libero di portare avanti lo sviluppo tramite una PR (possibilmente, avvisando con un commento, per evitare che in più persone si lavori inutilmente sullo stesso sviluppo).
Se qualcun altro, invece, dovesse avere altre opinioni a riguardo, non esiti a commentare ulteriormente questa Issue con le sue osservazioni.

**Comment by MarcoCalcagni** [comment]
Aggiunta la gestione company id
