### ISSUE TITLE
Campo standard x le note

### ISSUE THREAD

**Issue by andreampiovesana** [DinamicheAziendali/l10n_it_delivery_note#61]
Userei la stessa tipologia usata per ordini e fatture ovvero campo tipo text. E lo metterei a piede del documento della form. Inoltre il formato HTML non viene gestito nei report xlsxwriter.

**Comment by Byloth** [comment]
Se devo essere sincero, questa richiesta la trovo un "passo indietro" rispetto al comportamento attuale.  
Il campo `Html` consente esattamente le stesse funzioni offerte dal formato `Text`, oltre a tutta la libertà della formattazione del testo (cosa non offerta, invece, dal tipo `Text`).

Oltre al fatto che, se i report XLSX (formato **NON** standard di Odoo) non supportano correttamente questo tipo, il problema non è certo da ricercarsi in `l10n_it_delivery_note`...  
Forse, la PR, è da fare su suddetti moduli di reporting... 

---

> *Ma chi sono io, per dire ciò che è giusto e ciò che è sbagliato?* 🤔

Serve anche a qualcun altro, questa funzionalità?

**Comment by andreampiovesana** [comment]
tenere una linea standard per i documenti è MOLTO meglio:
sale.order
account.invoice
stock.picking
purchase.order
e
stock.delivery.note

Se trasferisco una nota da ordine a DDT e quindi a fattura è meglio se sono tutte dello stesso formato

Il giorno gio 18 giu 2020 alle ore 09:31 Matteo Bilotta <
notifications@github.com> ha scritto:

**Comment by MarcoCalcagni** [comment]
non è che esiste una funzione che pulisce i tag html? 
nei template per inviare le mail in automatico avevo lo stesso problema che ho risolto con 
${object.description | safe}

**Comment by Byloth** [comment]
Di seguito il codice interessato standard di Odoo:

https://github.com/odoo/odoo/blob/12.0/odoo/tools/mail.py#L286-L381

**Comment by Byloth** [comment]
A seguito di una call con @As400it, riassumo quanto è emerso:

- Utilizzare il campo `Text` anziché `Html` **È** un downgrade.
- Utilizzare il campo `Text` anziché `Html` perché quest'ultimo non è un tipo supportato dai report prodotti con XlsxWriter **NON** è una motivazione valida.  
Se XlsxWriter non supporta i campi `Html`, che si faccia una PR presso XlsxWriter.
- Utilizzare il campo `Text` anziché `Html` con la motivazione del «In Odoo standard funziona così.» **NON** è una motivazione valida (oltre che essere formalmente scorretto: i campi `Html` in Odoo vengono utilizzati).  
Se dovessimo applicare questo ragionamento per ogni modulo, perché stiamo ancora sviluppando questo modulo? Mica esiste il DdT in Odoo standard!
- Utilizzare il campo `Html` anziché `Text` consente, tramite la formattazione del testo, di mettere ben in evidenza eventuali informazioni importanti per il corriere.  
Un esempio di questa cosa potrebbe essere il rendere visibile in maniera molto chiara (per esempio evidenziando il testo in giallo, scrivendolo in rosso e/o in grassetto) che è necessario richiedere il pagamento alla consegna, nel caso si stia utilizzando il contrassegno come metodo di pagamento.

---

A seguito di questo, si è deciso di chiudere definitivamente questa Issue (quantomeno, fino a quando non verrà fornita una nuova motivazione ritenuta valida).
