### ISSUE TITLE
Possibile avere il commento ddt in fattura sopra il prodotto fatturato, per il prodotto il proprio commento ddt

### ISSUE THREAD

**Issue by Borruso** [DinamicheAziendali/l10n_it_delivery_note#66]

**Comment by Byloth** [comment]
Ciao @andreampiovesana!  
Puoi spiegarmi meglio, questa richiesta?

Se la fattura contiene 3 prodotti ed è associata ad un solo DdT, vorresti riportare 3 volte (una per prodotto) la stessa dicitura `DdT del ...` prima di ogni singolo prodotto?

**Comment by andreampiovesana** [comment]
il commento nr e data ddt della fattura deve essere posizionato prima delle
righe a cui si riferisce, come una intestazione
ad esempio
*DdT DDT/2020/123 del 01/06/2020*
mouse nr 1
tastiera nr 2
*DdT DDT/2020/456 del 06/06/2020*
monitor nr 1
patch 3 mt nr 10
patch 3 mt nr 10
evidenzierei in bold se commento oppure usando la sezione





Andrea Piovesana Linux Mint 19.3www.pnlug.it



Il giorno ven 10 lug 2020 alle ore 10:22 Matteo Bilotta <
notifications@github.com> ha scritto:

**Comment by Byloth** [comment]
Ah... Adesso ha più senso!  
Sì, ok... Ci sta!

Poichè, comunque, la procedura di creazione delle fatture non è custom (ma è standard Odoo), è necessario verificare quanto sia oneroso introdurre questo tipo di logica...

---

### Possibili pitfall! ⚠

- Quanto è oneroso o complicato capire quale riga di fattura è legata a quale DdT?  
Se sono presenti due DdT in fattura che presentano una stessa riga, con stesso prodotto, lo stesso prezzo e stesse quantità, come posso distinguerle ed essere certo di quale riga sia associata a quale DdT?
- I prodotti, inseriti in fattura, sono già ordinati e "separati" secondo una qualche logica oppure vengono inseriti ordinati per "Nome" oppure "ID" (non garantendo, quindi, una netta separazione e obbligandoci ad introdurre ANCHE questa logica di ordinamento)?
- Se vengono fatturati più ordini di vendita contemporaneamente (nel caso in cui siano legati allo stesso DdT) le righe dello stesso prodotto vengono raggruppate sommando le quantità oppure rimangono separate (sarei più orientato verso la seconda ipotesi)?  
Qualora, però, venissero sommate sarebbe impossibile dividere le righe da delle note.

**Comment by Byloth** [comment]
Ok... Dunque...

Ho sviluppato questa feature descritta e l'ho pushata nel branch separato [`feature/ddt-invoice-notes`](https://github.com/DinamicheAziendali/l10n_it_delivery_note/tree/feature/ddt-invoice-notes).  
Presenta, infatti, un piccolo problema ed è necessario capire come risolverlo.

Di seguito descritto...

---

Supponiamo questo caso...  
Dato un ordine di vendita di partenza, vengono associate in maniera "sfalsata" le righe a 3 picking differenti da cui, poi, verranno generati e confermati 3 DdT differenti.

A questo punto, sono presenti 3 DdT (legati, per forza di cose, allo stesso ordine di vendita):

- DDT/00001 (blu)
- DDT/00004 (verde)
- DDT/00005 (rosso)

Riporto, qui sotto una rappresentazione delle relazioni tra righe dell'ordine di vendita e DdT:

![order_lines](https://user-images.githubusercontent.com/14953974/88377564-b77ae480-cd9f-11ea-8e49-84d1c075a6d5.jpg)

Fatturiamo, ora, l'ordine di vendita...  
La logica corrente di questa feature non tocca minimamente quello che è l'ordine delle righe della fattura generata (che lascia invariate) ma, semplicemente, posiziona la relativa nota `DdT "<numero_ddt>" del <data>` subito prima alla prima riga con tale occorrenza...

Qui, un esempio del risultato finale con le relative relazioni colorate tra righe della fattura e DdT:

![invoice_lines](https://user-images.githubusercontent.com/14953974/88377876-3e2fc180-cda0-11ea-932d-62880a8334ab.jpg)

Come è facile evincere, quindi, il risultato finale può essere fuorviante...  
Sembra, infatti, che siano ben 3 le righe collegate al DDT/00001 (quando, in realtà, solo una di esse è associata a tale DdT).

Spero di aver reso l'idea generale del problema...

---

Quello che chiedo, adesso, è:  

- Come gestiamo questo caso?
- Dobbiamo riordinare, a prescindere, le righe della fattura generata?
  - E se, tali righe, fossero state ordinate secondo una logica particolare direttamente dall'operatore, nell'ordine di vendita?
- Possiamo considerare, tale caso, abbastanza "borderline" ed ignorarlo e mantenere la gestione così?
- Potremmo verificare, prima di aggiungere le righe note dei DdT, se sono ordinate?
  - Se non lo fossero, potremmo pensare di aggiungere in coda a tutte le righe fattura, le righe note dei DdT?

Decidiamo insieme, signori...

**Comment by Byloth** [comment]
Mi è giusto venuta in mente un'altra idea! 💡

Potremmo, eventualmente, aggiungere un flag a livello di configurazione che (se flaggato) riordini le righe per DdT.  
Così facendo, si lascerebbe all'utente finale l'onere di decidere se si vogliono le righe ordinate secondo l'ordine presente nell'ordine di vendita di partenza oppure secondo il DdT associato alla riga stessa.

---

### Possibili pitfall! ⚠

Se, per qualche motivo, una stessa riga dell'ordine di vendita fosse splittata su più DdT (per esempio: quantità totale 5 / 3 sul primo DdT / 2 sul secondo DdT), si avrebbero, comunque, problemi nel gestire l'ordinamento con le relative righe di note dei DdT.  
In tal caso, come andrebbe gestita, la cosa?

**Comment by gigidn** [comment]
Sta roba e' di borbonica concezione .... dopotutto anche la FE prevede uno o piu' DDT associati alla linea di fattura ... ordino 10 spedisco in 3 momenti fatturo in blocco .. l'intestazione seppur possibile (tutto si fa al mondo) e' fonte di innumerevoli bug e complicazioni inutili legati solo alle preferenze individuali ... io ero abituato cosi'.
La riga di fattura anche in stampa deve riportare i DDT a cui e' associata ... punto ... questo risolve il problema e rende coerente il tutto con FE ... se proprio si vuole si puo' ordinare sul report per la colonna ddt.
