### ISSUE TITLE
DdT non confermati associati a fatture

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#68]
@Borruso ha identificato un caso particolare (che prego di indicare, qui nei commenti, i passi necessari per riprodurlo) in cui risultano esserci dei DdT **NON CONFERMATI** associati a delle fatture.

È un caso che **NON** di deve verificare. Punto.

---

L'origine del problema sembra essere la mancanza dei valori dei campi `name` e `date` del DdT in questione.  
La fix proposta è stato un if statement per verificare e controllare la validità di questi campi.

Qui il commit in oggetto: https://github.com/DinamicheAziendali/l10n_it_delivery_note/commit/da3636eea7e77a19e3dfe6b0214e9936b37cae6d#diff-cc7043e70956d11fab0b6d8dcb61e95bL100-R117

Questa soluzione risolve nell'immediato il problema **NON** risalendo, però, all'origine del problema ed impedendo che ciò accada nuovamente. In gergo, questo, viene definita una "pezza".

---

È necessario capire come sia stato possibile che un DdT non confermato sia finito tra i DdT associati ad una fattura ed impedire che ciò accada nuovamente.  
Questa è l'unica soluzione a lungo termine valida.

**Comment by Byloth** [comment]
@As400it: metto anche te al corrente di questa problematica.

**Comment by Byloth** [comment]
Ora i test girano...  
La ragione del fallimento dei test, però, non è in alcun modo in relazione al problema indicato in questo ticket.

Rimane sconosciuta la sequenza di passi per replicare il problema.

**Comment by Borruso** [comment]
A questo punto dire che la causa di questo errore è dato dalla non congruenza tra la PR e questo repo.
La congruenza ormai è quasi nulla, entro oggi modificherò la PR con le modifiche applicate al repo.

**Comment by Byloth** [comment]
Se questo errore, non ti si dovesse più presentare, avvisa su questa Issue!

Così la _flagghiamo_ come risolta e la chiudiamo! 😉

**Comment by Byloth** [comment]
@Borruso?  
Abbiamo news riguardo a questo problema?

Possiamo considerarlo risolto e chiudere la Issue?

**Comment by Borruso** [comment]
@Byloth puoi chiudere!
Confermo che la causa di questo errore è dato dalla non congruenza, ormai è nulla, tra la PR e questo repo.
