### ISSUE TITLE
Inserire sia sul ddt sia su tipologia ddt il flag da fatturare

### ISSUE THREAD

**Issue by GrassoPao** [DinamicheAziendali/l10n_it_delivery_note#7]
Legato al flag da fatturare inserire anche uno state con i seguenti valori:
1  no  fattura
2 parzialmente fatturato
3 interamente fatturato
Entrambi i flag vanno inseriti nella lista e aggiunti i relativi filtri

**Comment by Byloth** [comment]
Potresti spiegarmi meglio questo ticket?  
Quale dovrebbe essere l'utilità di avere uno stato sulla tipologia del DdT?

Non sarebbe meglio avere, lo stesso stato, ma all'interno del DdT?

**Comment by Byloth** [comment]
Issue legata a #11

**Comment by Byloth** [comment]
Nel commit appena pushato è stata implementata la gestione dello stato di fatturazione del DdT.  
Inoltre, sono stati aggiunti i relativi filtri e raggruppamenti nella relativa `treeview`.

Rimane da capire il resto della segnalazione di @GrassoPao, come chiesto nel mio commento di ieri.

**Comment by MarcoCalcagni** [comment]
superata nello sprint
