### ISSUE TITLE
Funzionalità duplicata in `l10n_it_delivery_note_order_link`

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#70]
Buongiorno a tutti.

Richiamo l'attenzione di @andreampiovesana, per questa Issue. 

Stavo girovagando tra i file del progetto e mi son ritrovato di fronte a questa incongruenza.  
Tutte le logiche presenti in [questo file](https://github.com/DinamicheAziendali/l10n_it_delivery_note/blob/98545e5f50b548234dd266fbc028edc61d179f00/l10n_it_delivery_note_order_link/models/sale_order.py) sono già presenti (e quindi duplicate) in [quest'altro file](https://github.com/DinamicheAziendali/l10n_it_delivery_note/blob/98545e5f50b548234dd266fbc028edc61d179f00/l10n_it_delivery_note/models/sale_order.py).

Come mai?

**Comment by Byloth** [comment]
Ping, @andreampiovesana.

**Comment by andreampiovesana** [comment]
order link è il mio modulo ....
poi vedete voi ...

Andrea Piovesana Linux Mint 19.3www.pnlug.it



Il giorno ven 30 ott 2020 alle ore 09:57 Matteo Bilotta <
notifications@github.com> ha scritto:

**Comment by Byloth** [comment]
Sissì... Lo so bene, @andreampiovesana...
Nulla da obiettare, su questo punto...

> *«Date a Cesare quel che è di Cesare!»*

---

Ti ho solo chiesto, come mai, sono state duplicate delle logiche...
C'è un motivo in particolare, è un errore oppure è una semplice ridondanza?

Si può rimuovere o va lasciato lì?
E se "sì"... Perché?

**Comment by Byloth** [comment]
Ping, @andreampiovesana.

**Comment by andreampiovesana** [comment]
nel modulo principale forse è stato fatto dopo, è passato molto tempo e
moltissimi commit
io lo lascerei nel mio, ovviamente
grazie

Andrea Piovesana Linux Mint 19.3www.pnlug.it



Il giorno lun 9 nov 2020 alle ore 15:10 Matteo Bilotta <
notifications@github.com> ha scritto:

**Comment by Byloth** [comment]
Grazie per la risposta.  
Chiudo il ticket.
