### ISSUE TITLE
Picking di tipo mrp_operation partner non obbligatorio

### ISSUE THREAD

**Issue by Borruso** [DinamicheAziendali/l10n_it_delivery_note#73]
l'unico caso in cui la picking può non avere il partner è quando essa è in mrp_operation e in questo caso e pure inulite scatenare la creazione del ddt.
Per ricreare il caso basta fare:

- una picking senza partner e di tipo mrp_operation

- ubicazione di provenienza wh/stock

- destinazione virtual locations/production

**Comment by Byloth** [comment]
@As400it e @Borruso, provate a dare un occhio...
Ho pushato questo commit e dovrei aver risolto il problema indicato.

Dico "dovrei" perché, personalmente, non ho sufficiente esperienza con il modulo MRP...

Inoltre...
Ho rimosso quel blocco di `try: except:` che wrappava un `ValueError` per convertirla in una `UserError` (se ho ben capito, non dovrebbe più servire).

Fatemi sapere.

**Comment by Borruso** [comment]
Provato è funziona ottimo lavoro :+1: @Byloth
