### ISSUE TITLE
Migrazione DdT con sequence `range_year`

### ISSUE THREAD

**Issue by Byloth** [DinamicheAziendali/l10n_it_delivery_note#78]
Se si tenta di eseguire la migrazione dei dati, una volta passato il nuovo anno, la sequence restituirà come valore `1`.  
Così facendo, ne risulta che non avviene alcuna migrazione in quanto, la sequence, viene reputata come "nuova"!

Basarsi su una `search_count` anziché sulla sequence.

---

La sequence di `delivery_note` non sembra abbiano una logica di `range_year`!  
Verificare e correggere questo comportamento!

**Comment by Byloth** [comment]
La soluzione proposta da @GSLabIt è la seguente:

```python
old_sequence = self.env.ref('l10n_it_ddt.seq_ddt')
max_old_sequnce = max(old_sequence.mapped('date_range_ids'))
if max_old_sequnce == 1:
    raise UserError(_(
        "It seems that there are no documents to migrate. "
        "You don't need to run this command."
    ))
```

**Comment by GSLabIt** [comment]
fixata

```
old_sequence = self.env.ref('l10n_it_ddt.seq_ddt')
max_old_sequence = max(old_sequence.mapped('date_range_ids'))
if max_old_sequence == 1:
    raise UserError(_(
        "It seems that there are no documents to migrate. "
        "You don't need to run this command."
    ))
```

**Comment by Byloth** [comment]
Ho eliminato il commento precedente per evitare ridondanza.  
Ho corretto lo snippet nel mio commento precedente!

Grazie della fix! 😉
