### ISSUE TITLE
Stampa descrizione prodotto invece del nome nel DDT / riferimento interno duplicato

### ISSUE THREAD

**Issue by francesco-ooops** [DinamicheAziendali/l10n_it_delivery_note#86]
Al momento il campo "descrizione" del ddt riporta il nome del prodotto invece che la descrizione prodotto inserita nel SO

questa funzionalità (stampa descrizione) era presente nel vecchio ddt e la sua mancanza genera un'inconsistenza:

- la stampa SO contiene il campo "descrizione" e non il campo "nome"
- la stampa fattura contiene il campo "descrizione" e non il campo "nome"
- la stampa DDT contiene il campo nome 

si potrebbe modificare?

Inoltre nella stampa il riferimento interno prodotto appare duplicato in due colonne contigue:

![image](https://user-images.githubusercontent.com/55489873/105012024-f8e20900-5a3d-11eb-8873-03094f326b0f.png)

grazie

**Comment by Byloth** [comment]
@Borruso e @As400it: questa Issue fa riferimento ad uno degli errori già risolti... Sbaglio? 🤔
