### ISSUE TITLE
DN restano in stato "fatturato" anche se si elimina la fattura a loro collegata

### ISSUE THREAD

**Issue by francesco-ooops** [DinamicheAziendali/l10n_it_delivery_note#88]
Versioni coinvolte:

12.0

Passi per riprodurre:

creo ordine di vendita > confermo > valido picking > valido DDT > creo fattura

entro nella fattura appena creata > elimino fattura > torno nell'ordine > creo nuova fattura

Comportamento osservato: 

Il DDT resta in stato "fatturato" anche dopo l'eliminazione della fattura collegata
Non è presente il tasto "crea fattura" nel ddt
Se creo una nuova fattura dallo stesso ordine, non è presente il riferimento DDT in fattura

Comportamento atteso

All'eliminazione della fattura:
Il DDT dovrebbe tornare in stato "validato"
Dovrebbe tornare visibile il tasto "crea fattura" nel DDT
Se fatturo nuovamente l'ordine, dovrebbe essere visibile il riferimento DDT in fattura

Come da funzionamento standard tra SO/fattura

Video: https://recordit.co/SS3i2SkNYS

**Comment by Byloth** [comment]
Hai perfettamente ragione.  
Per la natura del DdT (piuttosto complessa, in realtà, potendo essere fatturato parzialmente e legato a diversi ordini contemporaneamente), al momento, non è possibile aggiornare autonomamente lo stato del DdT stesso.

Consiglio di Annullare il DdT, reimpostarlo a Bozza e rivalidarlo nuovamente; la numerazione verrà mantenuta.  
Così facendo, verrà aggiornato lo stato del DdT.

**Comment by Byloth** [comment]
Qualora fossi interessato a proporre una soluzione per questo problema, ti invito ad aprire una PR collegandola a questa Issue.

Fino ad allora, chiudo.
